/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { YoutubePlaylist } from "./YoutubePlaylist";
import { YoutubePlaylistCountArgs } from "./YoutubePlaylistCountArgs";
import { YoutubePlaylistFindManyArgs } from "./YoutubePlaylistFindManyArgs";
import { YoutubePlaylistFindUniqueArgs } from "./YoutubePlaylistFindUniqueArgs";
import { DeleteYoutubePlaylistArgs } from "./DeleteYoutubePlaylistArgs";
import { YoutubePlaylistService } from "../youtubePlaylist.service";
@graphql.Resolver(() => YoutubePlaylist)
export class YoutubePlaylistResolverBase {
  constructor(protected readonly service: YoutubePlaylistService) {}

  async _youtubePlaylistsMeta(
    @graphql.Args() args: YoutubePlaylistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [YoutubePlaylist])
  async youtubePlaylists(
    @graphql.Args() args: YoutubePlaylistFindManyArgs
  ): Promise<YoutubePlaylist[]> {
    return this.service.youtubePlaylists(args);
  }

  @graphql.Query(() => YoutubePlaylist, { nullable: true })
  async youtubePlaylist(
    @graphql.Args() args: YoutubePlaylistFindUniqueArgs
  ): Promise<YoutubePlaylist | null> {
    const result = await this.service.youtubePlaylist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => YoutubePlaylist)
  async deleteYoutubePlaylist(
    @graphql.Args() args: DeleteYoutubePlaylistArgs
  ): Promise<YoutubePlaylist | null> {
    try {
      return await this.service.deleteYoutubePlaylist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
